# Generated by Django 3.0.5 on 2020-05-11 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('logo', models.CharField(max_length=9999)),
            ],
        ),
        migrations.RenameField(
            model_name='productimage',
            old_name='mainimage',
            new_name='main_image',
        ),
        migrations.AddField(
            model_name='product',
            name='year_published',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='product',
            name='manufacturer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.Manufacturer'),
        ),
    ]
